
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
speed_to_erpm_gain: 4500  ## 4500
speed_to_erpm_offset: 300.0

# Set gains for converting acceleration to current and brake control values
accel_to_current_gain: 100
accel_to_brake_gain: -80

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 10.2 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 50.5 # meters/second^2
throttle_smoother_rate: 5000.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -0.62  ## -0.58
# steering_angle_to_servo_offset: 0.631 
steering_angle_to_servo_offset: 0.38

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm 
wheelbase: .25

vesc_driver:
  port: /dev/ttyVESC
  duty_cycle_min: 0.0
  duty_cycle_max: 1.0
  current_min: -100.0
  current_max: 100.0
  brake_min: -200000.0
  brake_max: 200000.0
  speed_min: -53250
  speed_max: 53250
  position_min: 0.0
  position_max: 0.0
  servo_min: -1
  servo_max: 1
